// Data tree structure for letluckdecide.com

export const DATA = {
    travel: {
        travel_root: {
            id: "travel_root",
            label: "Ταξιδεύω",
            children: ["travel_internal", "travel_abroad"]
        },
        travel_internal: {
            id: "travel_internal",
            label: "Εσωτερικό",
            children: ["internal_islands", "internal_mainland"]
        },
        travel_abroad: {
            id: "travel_abroad",
            label: "Εξωτερικό",
            children: ["abroad_europe", "abroad_asia", "abroad_middleeast"]
        },
        internal_islands: {
            id: "internal_islands",
            label: "Νησιά",
            children: ["islands_cyclades", "islands_dodecanese"]
        },
        internal_mainland: {
            id: "internal_mainland",
            label: "Ηπειρωτική",
            children: ["mainland_peloponnese", "mainland_sterea", "mainland_north"]
        },
        islands_cyclades: {
            id: "islands_cyclades",
            label: "Κυκλάδες",
            pool: [
                { id: "mykonos", label: "Μύκονος" },
                { id: "naxos", label: "Νάξος" },
                { id: "paros", label: "Πάρος" },
                { id: "sifnos", label: "Σίφνος" },
                { id: "ios", label: "Ίος" },
                { id: "milos", label: "Μήλος" },
                { id: "santorini", label: "Σαντορίνη" },
                { id: "tinos", label: "Τήνος" },
                { id: "andros", label: "Άνδρος" },
                { id: "syros", label: "Σύρος" },
                { id: "folegandros", label: "Φολέγανδρος" },
                { id: "amorgos", label: "Αμόργος" },
                { id: "serifos", label: "Σέριφος" },
                { id: "kea", label: "Κέα" },
                { id: "kythnos", label: "Κύθνος" },
                { id: "antiparos", label: "Αντίπαρος" },
                { id: "koufonisia", label: "Κουφονήσια" },
                { id: "schinousa", label: "Σχοινούσα" },
                { id: "donousa", label: "Δονούσα" },
                { id: "kimolos", label: "Κίμωλος" },
                { id: "anafi", label: "Ανάφη" },
                { id: "sikinos", label: "Σίκινος" },
                { id: "irakleia", label: "Ηρακλειά" },
                { id: "delos", label: "Δήλος" },
                { id: "gyaros", label: "Γυάρος" }
            ]
        },
        islands_dodecanese: {
            id: "islands_dodecanese",
            label: "Δωδεκάνησα",
            pool: [
                { id: "rodos", label: "Ρόδος" },
                { id: "kos", label: "Κως" },
                { id: "kalymnos", label: "Κάλυμνος" },
                { id: "symi", label: "Σύμη" },
                { id: "karpathos", label: "Κάρπαθος" },
                { id: "kasos", label: "Κάσος" },
                { id: "leros", label: "Λέρος" },
                { id: "patmos", label: "Πάτμος" },
                { id: "nisyros", label: "Νίσυρος" },
                { id: "astypalaia", label: "Αστυπάλαια" },
                { id: "chalki", label: "Χάλκη" },
                { id: "lipsi", label: "Λείψοι" },
                { id: "tilos", label: "Τήλος" },
                { id: "telendos", label: "Τέλενδος" },
                { id: "agathonisi", label: "Αγαθονήσι" },
                { id: "arkoi", label: "Αρκοί" },
                { id: "farmakonisi", label: "Φαρμακονήσι" },
                { id: "leipsoi", label: "Λειψοί" },
                { id: "pserimos", label: "Ψέριμος" },
                { id: "ro", label: "Ρω" }
            ]
        },
        mainland_peloponnese: {
            id: "mainland_peloponnese",
            label: "Πελοπόννησος",
            pool: [
                { id: "kalamata", label: "Καλαμάτα" },
                { id: "nafplio", label: "Ναύπλιο" },
                { id: "monemvasia", label: "Μονεμβασιά" },
                { id: "sparti", label: "Σπάρτη" },
                { id: "tripoli", label: "Τρίπολη" },
                { id: "dimitsana", label: "Δημητσάνα" },
                { id: "kalavryta", label: "Καλάβρυτα" },
                { id: "olympia", label: "Ολυμπία" },
                { id: "pylos", label: "Πύλος" },
                { id: "methoni", label: "Μεθώνη" },
                { id: "koroni", label: "Κορώνη" },
                { id: "areopoli", label: "Αρεόπολη" },
                { id: "gytheio", label: "Γύθειο" },
                { id: "mani", label: "Μάνη" },
                { id: "leonidio", label: "Λεωνίδιο" },
                { id: "kastro", label: "Κάστρο (Κυθύρειας)" },
                { id: "kyparissia", label: "Κυπαρισσία" },
                { id: "stoupa", label: "Στούπα" },
                { id: "kardamyli", label: "Καρδαμύλη" },
                { id: "kythira", label: "Κύθηρα" },
                { id: "argos", label: "Άργος" },
                { id: "mycenae", label: "Μυκήνες" },
                { id: "epidaurus", label: "Επίδαυρος" },
                { id: "nemea", label: "Νεμέα" }
            ]
        },
        mainland_sterea: {
            id: "mainland_sterea",
            label: "Στερεά Ελλάδα",
            pool: [
                { id: "delphi", label: "Δελφοί" },
                { id: "galaxidi", label: "Γαλαξίδι" },
                { id: "karpenisi", label: "Καρπενήσι" },
                { id: "lamia", label: "Λαμία" },
                { id: "arachova", label: "Αράχωβα" },
                { id: "livadia", label: "Λιβαδειά" },
                { id: "ioannina", label: "Ιωάννινα" },
                { id: "metsovo", label: "Μέτσοβο" },
                { id: "zagorochoria", label: "Ζαγοροχώρια" },
                { id: "preveza", label: "Πρέβεζα" },
                { id: "parga", label: "Πάργα" },
                { id: "igoumenitsa", label: "Ηγουμενίτσα" },
                { id: "arta", label: "Άρτα" },
                { id: "agrinio", label: "Αγρίνιο" },
                { id: "messolonghi", label: "Μεσολόγγι" },
                { id: "nafpaktos", label: "Ναύπακτος" },
                { id: "ithea", label: "Ιτέα" },
                { id: "kyllini", label: "Κυλλήνη" },
                { id: "patras", label: "Πάτρα" },
                { id: "kalavrita", label: "Καλαβρύτα" }
            ]
        },
        mainland_north: {
            id: "mainland_north",
            label: "Βόρεια Ελλάδα",
            pool: [
                { id: "thessaloniki", label: "Θεσσαλονίκη" },
                { id: "chalkidiki", label: "Χαλκιδική" },
                { id: "kavala", label: "Καβάλα" },
                { id: "drama", label: "Δράμα" },
                { id: "xanthi", label: "Ξάνθη" },
                { id: "komotini", label: "Κομοτηνή" },
                { id: "alexandroupoli", label: "Αλεξανδρούπολη" },
                { id: "ioannina", label: "Ιωάννινα" },
                { id: "zagorochoria", label: "Ζαγοροχώρια" },
                { id: "metsovo", label: "Μέτσοβο" },
                { id: "kastoria", label: "Καστοριά" },
                { id: "florina", label: "Φλώρινα" },
                { id: "prespes", label: "Πρέσπες" },
                { id: "veria", label: "Βέροια" },
                { id: "naousa", label: "Νάουσα" },
                { id: "edessa", label: "Έδεσσα" },
                { id: "aridaia", label: "Αριδαία" },
                { id: "pella", label: "Πέλλα" },
                { id: "litochoro", label: "Λιτόχωρο" },
                { id: "leptokarya", label: "Λεπτοκαρυά" },
                { id: "plaka_litochorou", label: "Πλάκα Λιτοχώρου" },
                { id: "katerini", label: "Κατερίνη" },
                { id: "mount_olympus", label: "Όλυμπος" },
                { id: "meteora", label: "Μετέωρα" },
                { id: "kalampaka", label: "Καλαμπάκα" }
            ]
        },
        abroad_europe: {
            id: "abroad_europe",
            label: "Ευρώπη",
            pool: [
                { id: "rome", label: "Ρώμη" },
                { id: "paris", label: "Παρίσι" },
                { id: "barcelona", label: "Βαρκελώνη" },
                { id: "lisbon", label: "Λισαβόνα" },
                { id: "prague", label: "Πράγα" },
                { id: "vienna", label: "Βιέννη" },
                { id: "budapest", label: "Βουδαπέστη" },
                { id: "amsterdam", label: "Άμστερνταμ" },
                { id: "berlin", label: "Βερολίνο" },
                { id: "munich", label: "Μόναχο" },
                { id: "stockholm", label: "Στοκχόλμη" },
                { id: "copenhagen", label: "Κοπεγχάγη" },
                { id: "zurich", label: "Ζυρίχη" },
                { id: "london", label: "Λονδίνο" },
                { id: "edinburgh", label: "Εδιμβούργο" },
                { id: "dublin", label: "Δουβλίνο" },
                { id: "brussels", label: "Βρυξέλλες" },
                { id: "bruges", label: "Μπριζ" },
                { id: "madrid", label: "Μαδρίτη" },
                { id: "seville", label: "Σεβίλλη" },
                { id: "porto", label: "Πόρτο" },
                { id: "sintra", label: "Σίντρα" },
                { id: "krakow", label: "Κρακοβία" },
                { id: "warsaw", label: "Βαρσοβία" },
                { id: "bucharest", label: "Βουκουρέστι" },
                { id: "sarajevo", label: "Σαράγεβο" },
                { id: "dubrovnik", label: "Ντουμπρόβνικ" },
                { id: "split", label: "Σπλιτ" },
                { id: "oslo", label: "Όσλο" },
                { id: "bergen", label: "Μπέργκεν" },
                { id: "reykjavik", label: "Ρέικιαβικ" }
            ]
        },
        abroad_asia: {
            id: "abroad_asia",
            label: "Ασία",
            pool: [
                { id: "vietnam", label: "Βιετνάμ" },
                { id: "thailand", label: "Ταϊλάνδη" },
                { id: "japan", label: "Ιαπωνία" },
                { id: "south_korea", label: "Νότια Κορέα" },
                { id: "indonesia", label: "Ινδονησία" },
                { id: "malaysia", label: "Μαλαισία" },
                { id: "singapore", label: "Σιγκαπούρη" },
                { id: "philippines", label: "Φιλιππίνες" },
                { id: "india", label: "Ινδία" },
                { id: "sri_lanka", label: "Σρι Λάνκα" },
                { id: "cambodia", label: "Καμπότζη" },
                { id: "laos", label: "Λάος" },
                { id: "myanmar", label: "Μυανμάρ" },
                { id: "taiwan", label: "Ταϊβάν" },
                { id: "hong_kong", label: "Χονγκ Κονγκ" },
                { id: "china", label: "Κίνα" },
                { id: "mongolia", label: "Μογγολία" },
                { id: "nepal", label: "Νεπάλ" },
                { id: "bhutan", label: "Μπουτάν" },
                { id: "bangladesh", label: "Μπανγκλαντές" },
                { id: "pakistan", label: "Πακιστάν" },
                { id: "kazakhstan", label: "Καζακστάν" },
                { id: "uzbekistan", label: "Ουζμπεκιστάν" },
                { id: "kyrgyzstan", label: "Κιργιστάν" },
                { id: "tajikistan", label: "Τατζικιστάν" }
            ]
        },
        abroad_middleeast: {
            id: "abroad_middleeast",
            label: "Μ. Ανατολή",
            pool: [
                { id: "dubai", label: "Ντουμπάι" },
                { id: "abu_dhabi", label: "Αμπού Ντάμπι" },
                { id: "doha", label: "Ντόχα" },
                { id: "oman", label: "Ομάν" },
                { id: "jordan", label: "Ιορδανία" },
                { id: "beirut", label: "Βηρυτός" },
                { id: "istanbul", label: "Κωνσταντινούπολη" },
                { id: "cappadocia", label: "Καππαδοκία" },
                { id: "bodrum", label: "Μπόντρουμ" },
                { id: "antalya", label: "Ανταλία" },
                { id: "kuwait", label: "Κουβέιτ" },
                { id: "bahrain", label: "Μπαχρέιν" },
                { id: "riyadh", label: "Ριάντ" },
                { id: "jeddah", label: "Τζέντα" },
                { id: "muscat", label: "Μουσκάτ" }
            ]
        }
    },
    food: {
        food_root: {
            id: "food_root",
            label: "Μαγειρεύω",
            children: ["food_quick", "food_comfort", "food_healthy", "food_party"]
        },
        food_quick: {
            id: "food_quick",
            label: "Γρήγορο (≤20')",
            pool: [
                { id: "toast", label: "Τοστ" },
                { id: "omelette", label: "Ομελέτα" },
                { id: "pasta_aglio", label: "Μακαρόνια aglio e olio" },
                { id: "caesar_salad", label: "Σαλάτα Caesar" },
                { id: "lentil_salad", label: "Σαλάτα φακές" },
                { id: "chicken_sandwich", label: "Σάντουιτς κοτόπουλο" },
                { id: "quesadilla", label: "Quesadilla" },
                { id: "rice_veggies", label: "Ρύζι με λαχανικά" },
                { id: "noodles", label: "Noodles" },
                { id: "tuna_melt", label: "Tuna melt" },
                { id: "bruschetta", label: "Bruschetta" },
                { id: "dakos", label: "Ντάκος" },
                { id: "feta_pasta", label: "Φέτα pasta" },
                { id: "scrambled_eggs", label: "Αυγά σκαμμένα" },
                { id: "tacos", label: "Tacos" },
                { id: "pita_gyro", label: "Πιτάκια γύρος" },
                { id: "stir_fry", label: "Stir fry" },
                { id: "soup_quick", label: "Σούπα (γρήγορη)" },
                { id: "pancakes", label: "Πανκέικες" },
                { id: "waffles", label: "Βάφλες" },
                { id: "burrito_bowl", label: "Burrito bowl" },
                { id: "fried_rice", label: "Ρύζι τηγανητό" },
                { id: "pasta_pesto", label: "Μακαρόνια pesto" },
                { id: "shakshuka", label: "Shakshuka" },
                { id: "avocado_toast", label: "Avocado toast" },
                { id: "egg_fried_rice", label: "Ρύζι με αυγό" },
                { id: "carbonara_quick", label: "Carbonara (γρήγορη)" },
                { id: "cheese_omelette", label: "Ομελέτα τυρί" },
                { id: "tuna_salad", label: "Σαλάτα τόνος" },
                { id: "hummus_wrap", label: "Wrap με hummus" },
                { id: "pasta_tomato", label: "Μακαρόνια ντομάτα" },
                { id: "egg_sandwich", label: "Σάντουιτς αυγό" },
                { id: "caprese_salad", label: "Σαλάτα Caprese" },
                { id: "pasta_butter", label: "Μακαρόνια βούτυρο" },
                { id: "grilled_cheese", label: "Grilled cheese" },
                { id: "ramen_quick", label: "Ramen (γρήγορο)" },
                { id: "quesadilla_cheese", label: "Quesadilla τυρί" },
                { id: "eggs_benedict", label: "Eggs Benedict" },
                { id: "frittata", label: "Frittata" },
                { id: "sandwich_club", label: "Club sandwich" }
            ]
        },
        food_comfort: {
            id: "food_comfort",
            label: "Παρηγοριά / Comfort",
            pool: [
                { id: "pastitsio", label: "Παστίτσιο" },
                { id: "moussaka", label: "Μουσακάς" },
                { id: "spaghetti_meat", label: "Μακαρόνια με κιμά" },
                { id: "giouvetsi", label: "Γιουβέτσι" },
                { id: "pizza", label: "Πίτσα" },
                { id: "burger", label: "Burger" },
                { id: "chicken_potatoes", label: "Κοτόπουλο με πατάτες" },
                { id: "lasagna", label: "Lasagna" },
                { id: "ramen", label: "Ramen" },
                { id: "mac_cheese", label: "Mac & cheese" },
                { id: "shepherds_pie", label: "Shepherd's pie" },
                { id: "chili", label: "Chili con carne" },
                { id: "beef_stew", label: "Στιφάδο" },
                { id: "chicken_parmesan", label: "Chicken parmesan" },
                { id: "meatballs", label: "Κεφτέδες" },
                { id: "pasta_bolognese", label: "Μακαρόνια bolognese" },
                { id: "fried_chicken", label: "Τηγανιτό κοτόπουλο" },
                { id: "potatoes_oven", label: "Πατάτες φούρνου" },
                { id: "makaronia_kima", label: "Μακαρόνια κοκκινιστά με κιμά" },
                { id: "stifado", label: "Στιφάδο κουνέλι" },
                { id: "spetzofai", label: "Σπετζοφάι" },
                { id: "baked_ziti", label: "Baked ziti" },
                { id: "chicken_pot_pie", label: "Chicken pot pie" },
                { id: "beef_roast", label: "Βοδινό ψητό" },
                { id: "pasta_alfredo", label: "Μακαρόνια alfredo" },
                { id: "sloppy_joes", label: "Sloppy joes" },
                { id: "nachos", label: "Nachos" },
                { id: "quesadillas_comfort", label: "Quesadillas" },
                { id: "enchiladas", label: "Enchiladas" },
                { id: "tacos_comfort", label: "Tacos" },
                { id: "chicken_wings", label: "Φτερούγες κοτόπουλου" },
                { id: "pork_roast", label: "Χοιρινό ψητό" },
                { id: "meatloaf", label: "Meatloaf" },
                { id: "chicken_tenders", label: "Chicken tenders" },
                { id: "fish_chips", label: "Fish & chips" },
                { id: "poutine", label: "Poutine" },
                { id: "corn_dogs", label: "Corn dogs" },
                { id: "onion_rings", label: "Onion rings" },
                { id: "loaded_fries", label: "Loaded fries" },
                { id: "pasta_carbonara", label: "Carbonara" }
            ]
        },
        food_healthy: {
            id: "food_healthy",
            label: "Υγιεινό / Ελαφρύ",
            pool: [
                { id: "quinoa_salad", label: "Σαλάτα κινόα" },
                { id: "salmon_veggies", label: "Σολομός με λαχανικά" },
                { id: "chicken_grill_salad", label: "Κοτόπουλο σχάρας με σαλάτα" },
                { id: "lentils", label: "Φακές" },
                { id: "chickpeas_lemon", label: "Ρεβύθια λεμονάτα" },
                { id: "roasted_veggies", label: "Ψητά λαχανικά" },
                { id: "overnight_oats", label: "Overnight oats" },
                { id: "yogurt_fruits", label: "Γιαούρτι με φρούτα" },
                { id: "smoothie_bowl", label: "Smoothie bowl" },
                { id: "buddha_bowl", label: "Buddha bowl" },
                { id: "grilled_fish", label: "Ψαρικό ψητό" },
                { id: "chicken_salad_healthy", label: "Σαλάτα κοτόπουλο" },
                { id: "tuna_salad_healthy", label: "Σαλάτα τόνος" },
                { id: "avocado_salad", label: "Σαλάτα avocado" },
                { id: "greek_salad", label: "Ελληνική σαλάτα" },
                { id: "mediterranean_bowl", label: "Mediterranean bowl" },
                { id: "zucchini_noodles", label: "Zucchini noodles" },
                { id: "cauliflower_rice", label: "Cauliflower rice" },
                { id: "stuffed_peppers", label: "Γεμιστά πιπεριές" },
                { id: "stuffed_tomatoes", label: "Γεμιστές ντομάτες" },
                { id: "chicken_stir_fry", label: "Stir fry κοτόπουλο" },
                { id: "salmon_bowl", label: "Salmon bowl" },
                { id: "tuna_steak", label: "Στείρια τόνου" },
                { id: "chicken_breast", label: "Στήθος κοτόπουλο" },
                { id: "turkey_breast", label: "Στήθος γαλοπούλα" },
                { id: "egg_white_omelette", label: "Ομελέτα ασπράδια" },
                { id: "cottage_cheese_bowl", label: "Cottage cheese bowl" },
                { id: "chia_pudding", label: "Chia pudding" },
                { id: "acai_bowl", label: "Acai bowl" },
                { id: "green_smoothie", label: "Πράσινο smoothie" },
                { id: "protein_salad", label: "Σαλάτα πρωτεΐνης" },
                { id: "grilled_veggies", label: "Λαχανικά σχάρας" },
                { id: "steamed_fish", label: "Ψάρι στον ατμό" },
                { id: "lentil_soup", label: "Σούπα φακές" },
                { id: "chicken_soup", label: "Σούπα κοτόπουλο" },
                { id: "vegetable_soup", label: "Σούπα λαχανικά" },
                { id: "black_bean_salad", label: "Σαλάτα μαύρα φασόλια" },
                { id: "quinoa_stuffed", label: "Γεμιστά με κινόα" },
                { id: "fish_tacos", label: "Fish tacos" },
                { id: "chicken_ceasar_wrap", label: "Wrap Caesar κοτόπουλο" }
            ]
        },
        food_party: {
            id: "food_party",
            label: "Για παρέα / Τσιμπολόγημα",
            pool: [
                { id: "nachos_party", label: "Nachos" },
                { id: "wings", label: "Wings" },
                { id: "sliders", label: "Sliders" },
                { id: "pitakia", label: "Πιτάκια" },
                { id: "keftedakia", label: "Κεφτεδάκια" },
                { id: "homemade_fries", label: "Σπιτικές πατάτες" },
                { id: "cheese_plate", label: "Πλατό τυριών" },
                { id: "hummus_sticks", label: "Hummus + sticks" },
                { id: "guacamole", label: "Guacamole" },
                { id: "spring_rolls", label: "Spring rolls" },
                { id: "mozzarella_sticks", label: "Mozzarella sticks" },
                { id: "onion_rings_party", label: "Onion rings" },
                { id: "chicken_fingers", label: "Chicken fingers" },
                { id: "quesadillas_party", label: "Quesadillas" },
                { id: "tacos_party", label: "Tacos" },
                { id: "buffalo_cauliflower", label: "Buffalo cauliflower" },
                { id: "stuffed_mushrooms", label: "Γεμιστά μανιτάρια" },
                { id: "bruschetta_party", label: "Bruschetta" },
                { id: "caprese_skewers", label: "Caprese skewers" },
                { id: "cucumber_bites", label: "Cucumber bites" },
                { id: "pigs_in_blanket", label: "Pigs in a blanket" },
                { id: "deviled_eggs", label: "Deviled eggs" },
                { id: "spinach_dip", label: "Spinach dip" },
                { id: "artichoke_dip", label: "Artichoke dip" },
                { id: "shrimp_cocktail", label: "Shrimp cocktail" },
                { id: "cheese_ball", label: "Cheese ball" },
                { id: "meatballs_party", label: "Μπιφτέκια" },
                { id: "stuffed_peppers_party", label: "Γεμιστές πιπεριές" },
                { id: "chicken_satay", label: "Chicken satay" },
                { id: "potato_skins", label: "Potato skins" },
                { id: "pita_chips_dip", label: "Pita chips + dip" },
                { id: "baked_brie", label: "Baked brie" },
                { id: "crostini", label: "Crostini" },
                { id: "endive_appetizers", label: "Endive appetizers" },
                { id: "mini_quiches", label: "Mini quiches" },
                { id: "crackers_cheese", label: "Crackers + cheese" },
                { id: "olives_plate", label: "Πλατό ελιές" },
                { id: "tzatziki_pita", label: "Τζατζίκι + πιτάκια" },
                { id: "taramasalata", label: "Ταραμοσαλάτα" },
                { id: "fried_calamari", label: "Καλαμαράκια τηγανητά" }
            ]
        }
    },
    fun: {
        fun_root: {
            id: "fun_root",
            label: "Διασκεδάζω",
            children: ["fun_chill", "fun_hype", "fun_outdoor", "fun_indoor"]
        },
        fun_chill: {
            id: "fun_chill",
            label: "Chill",
            children: ["fun_chill_solo", "fun_chill_company"]
        },
        fun_hype: {
            id: "fun_hype",
            label: "Hype",
            children: ["fun_hype_company", "fun_hype_date"]
        },
        fun_outdoor: {
            id: "fun_outdoor",
            label: "Outdoor",
            children: ["fun_outdoor_day", "fun_outdoor_night"]
        },
        fun_indoor: {
            id: "fun_indoor",
            label: "Indoor",
            children: ["fun_indoor_relax", "fun_indoor_activity"]
        },
        fun_chill_solo: {
            id: "fun_chill_solo",
            label: "Μόνος/η",
            pool: [
                { id: "cinema_solo", label: "Σινεμά" },
                { id: "theater_solo", label: "Θέατρο" },
                { id: "reading_cafe", label: "Διαβάζω σε καφετέρια" },
                { id: "walk_solo", label: "Βόλτα" },
                { id: "park_bench", label: "Πάρκο - πάγκο" },
                { id: "museum_solo", label: "Μουσείο" },
                { id: "gallery_solo", label: "Γκαλερί" },
                { id: "bookstore", label: "Βιβλιοπωλείο" },
                { id: "coffee_solo", label: "Καφές ήσυχα" },
                { id: "beach_solo", label: "Παραλία" },
                { id: "yoga_park", label: "Yoga στο πάρκο" },
                { id: "photography_walk", label: "Φωτογραφική βόλτα" },
                { id: "library", label: "Βιβλιοθήκη" },
                { id: "gardening", label: "Κηπουρική" },
                { id: "drawing", label: "Σχεδίαση" },
                { id: "writing", label: "Γράψιμο" },
                { id: "meditation", label: "Διαλογισμός" },
                { id: "podcast_walk", label: "Βόλτα με podcast" },
                { id: "sunset_watch", label: "Ηλιοβασίλεμα" },
                { id: "picnic_solo", label: "Πικνίκ (μόνος)" },
                { id: "cycling_solo", label: "Ποδηλατική βόλτα" },
                { id: "fishing", label: "Ψάρεμα" },
                { id: "hammock", label: "Κρεβάτι (hammock)" },
                { id: "spa_day", label: "Spa day" },
                { id: "massage", label: "Μασάζ" },
                { id: "bath_relax", label: "Μπάνιο χαλάρωσης" },
                { id: "netflix_marathon", label: "Netflix marathon" },
                { id: "cooking_solo", label: "Μαγείρεμα (μόνος)" },
                { id: "baking_solo", label: "Ζαχαροπλαστική" },
                { id: "puzzle", label: "Puzzle" },
                { id: "crossword", label: "Crossword" },
                { id: "journaling", label: "Journaling" },
                { id: "music_listening", label: "Ακούω μουσική" },
                { id: "stargazing", label: "Αστρονομία" },
                { id: "bird_watching", label: "Παρατήρηση πουλιών" }
            ]
        },
        fun_chill_company: {
            id: "fun_chill_company",
            label: "Με παρέα",
            pool: [
                { id: "brunch", label: "Brunch" },
                { id: "coffee_chat", label: "Καφές με φίλους" },
                { id: "wine_bar", label: "Wine bar" },
                { id: "rooftop_drink", label: "Rooftop ποτό" },
                { id: "park_picnic", label: "Πικνίκ στο πάρκο" },
                { id: "beach_day", label: "Παραλία (μέρα)" },
                { id: "beach_evening", label: "Παραλία (βράδυ)" },
                { id: "cinema_friends", label: "Σινεμά με φίλους" },
                { id: "theater_friends", label: "Θέατρο με παρέα" },
                { id: "standup_comedy", label: "Stand-up comedy" },
                { id: "live_music", label: "Live μουσική" },
                { id: "jazz_bar", label: "Jazz bar" },
                { id: "board_games", label: "Επιτραπέζια" },
                { id: "game_night", label: "Game night" },
                { id: "cooking_night", label: "Cooking night" },
                { id: "potluck", label: "Potluck" },
                { id: "movie_night", label: "Movie night" },
                { id: "trivia_night", label: "Trivia night" },
                { id: "karaoke", label: "Karaoke" },
                { id: "bowling", label: "Bowling" },
                { id: "billiards", label: "Μπιλιάρδο" },
                { id: "museum_day", label: "Museum day" },
                { id: "gallery_visit", label: "Επίσκεψη γκαλερί" },
                { id: "book_club", label: "Book club" },
                { id: "wine_tasting", label: "Wine tasting" },
                { id: "cheese_tasting", label: "Cheese tasting" },
                { id: "cooking_class", label: "Cooking class" },
                { id: "painting_class", label: "Painting class" },
                { id: "yoga_class", label: "Yoga class" },
                { id: "spa_day_friends", label: "Spa day με φίλους" },
                { id: "beach_volleyball", label: "Beach volleyball" },
                { id: "sunset_watch_friends", label: "Ηλιοβασίλεμα με παρέα" },
                { id: "photography_walk_friends", label: "Φωτογραφική βόλτα" },
                { id: "hiking_easy", label: "Εύκολη πεζοπορία" },
                { id: "picnic_friends", label: "Πικνίκ με φίλους" }
            ]
        },
        fun_hype_company: {
            id: "fun_hype_company",
            label: "Με παρέα",
            pool: [
                { id: "club", label: "Club" },
                { id: "bar_hopping", label: "Bar hopping" },
                { id: "party", label: "Πάρτι" },
                { id: "concert", label: "Συναυλία" },
                { id: "festival", label: "Φεστιβάλ" },
                { id: "rave", label: "Rave" },
                { id: "pub_crawl", label: "Pub crawl" },
                { id: "karaoke_night", label: "Karaoke night" },
                { id: "dance_class", label: "Dance class" },
                { id: "escape_room", label: "Escape room" },
                { id: "paintball", label: "Paintball" },
                { id: "laser_tag", label: "Laser tag" },
                { id: "go_karts", label: "Go-karts" },
                { id: "arcade", label: "Arcade" },
                { id: "virtual_reality", label: "Virtual reality" },
                { id: "trampoline_park", label: "Trampoline park" },
                { id: "axe_throwing", label: "Axe throwing" },
                { id: "bubble_soccer", label: "Bubble soccer" },
                { id: "indoor_skydiving", label: "Indoor skydiving" },
                { id: "rock_climbing_gym", label: "Rock climbing (gym)" },
                { id: "bungee_jumping", label: "Bungee jumping" },
                { id: "zip_line", label: "Zip line" },
                { id: "surfing", label: "Surfing" },
                { id: "jet_ski", label: "Jet ski" },
                { id: "parasailing", label: "Parasailing" },
                { id: "skydiving", label: "Skydiving" },
                { id: "bungee_trampoline", label: "Bungee trampoline" },
                { id: "rope_course", label: "Rope course" },
                { id: "rafting", label: "Rafting" },
                { id: "kayaking", label: "Kayaking" },
                { id: "wakeboarding", label: "Wakeboarding" },
                { id: "snowboarding", label: "Snowboarding" },
                { id: "skiing", label: "Skiing" },
                { id: "mountain_biking", label: "Mountain biking" },
                { id: "atv_ride", label: "ATV ride" }
            ]
        },
        fun_hype_date: {
            id: "fun_hype_date",
            label: "Ραντεβού",
            pool: [
                { id: "concert_date", label: "Συναυλία" },
                { id: "club_date", label: "Club" },
                { id: "festival_date", label: "Φεστιβάλ" },
                { id: "dance_date", label: "Dance class" },
                { id: "escape_room_date", label: "Escape room" },
                { id: "karaoke_date", label: "Karaoke" },
                { id: "go_karts_date", label: "Go-karts" },
                { id: "paintball_date", label: "Paintball" },
                { id: "laser_tag_date", label: "Laser tag" },
                { id: "arcade_date", label: "Arcade" },
                { id: "virtual_reality_date", label: "Virtual reality" },
                { id: "trampoline_date", label: "Trampoline park" },
                { id: "rock_climbing_date", label: "Rock climbing" },
                { id: "mini_golf", label: "Mini golf" },
                { id: "battle_arcade", label: "Battle arcade" },
                { id: "bubble_soccer_date", label: "Bubble soccer" },
                { id: "axe_throwing_date", label: "Axe throwing" },
                { id: "comedy_show", label: "Comedy show" },
                { id: "live_music_date", label: "Live μουσική" },
                { id: "jazz_club", label: "Jazz club" },
                { id: "rooftop_bar", label: "Rooftop bar" },
                { id: "cocktail_bar", label: "Cocktail bar" },
                { id: "wine_bar_date", label: "Wine bar" },
                { id: "speakeasy", label: "Speakeasy" },
                { id: "dinner_show", label: "Dinner show" },
                { id: "dance_floor", label: "Dance floor" },
                { id: "salsa_night", label: "Salsa night" },
                { id: "trivia_night_date", label: "Trivia night" },
                { id: "game_bar", label: "Game bar" },
                { id: "board_game_cafe", label: "Board game café" },
                { id: "bike_ride", label: "Ποδηλατική βόλτα" },
                { id: "sunset_spot", label: "Sunset spot" },
                { id: "adventure_park", label: "Adventure park" },
                { id: "ferris_wheel", label: "Ferris wheel" },
                { id: "amusement_park", label: "Luna park" }
            ]
        },
        fun_outdoor_day: {
            id: "fun_outdoor_day",
            label: "Μέρα",
            pool: [
                { id: "hiking", label: "Πεζοπορία" },
                { id: "beach_day_outdoor", label: "Παραλία" },
                { id: "picnic_outdoor", label: "Πικνίκ" },
                { id: "cycling", label: "Ποδηλατική" },
                { id: "park_walk", label: "Βόλτα πάρκο" },
                { id: "beach_volleyball_outdoor", label: "Beach volleyball" },
                { id: "swimming", label: "Κολύμπι" },
                { id: "snorkeling", label: "Snorkeling" },
                { id: "surfing_day", label: "Surfing" },
                { id: "kayaking_day", label: "Kayaking" },
                { id: "paddleboarding", label: "Paddleboarding" },
                { id: "sailing", label: "Ιστιοπλοΐα" },
                { id: "fishing_day", label: "Ψάρεμα" },
                { id: "camping", label: "Κατασκήνωση" },
                { id: "road_trip", label: "Road trip" },
                { id: "photography_outdoor", label: "Φωτογραφία" },
                { id: "bird_watching_outdoor", label: "Παρατήρηση πουλιών" },
                { id: "gardening_outdoor", label: "Κηπουρική" },
                { id: "barbecue", label: "Barbecue" },
                { id: "outdoor_yoga", label: "Yoga" },
                { id: "running", label: "Τρέξιμο" },
                { id: "jogging", label: "Jogging" },
                { id: "basketball_outdoor", label: "Μπάσκετ" },
                { id: "football_outdoor", label: "Ποδόσφαιρο" },
                { id: "tennis", label: "Tennis" },
                { id: "golf", label: "Golf" },
                { id: "rock_climbing_outdoor", label: "Rock climbing" },
                { id: "mountain_biking_outdoor", label: "Mountain biking" },
                { id: "atv_day", label: "ATV" },
                { id: "horseback_riding", label: "Ιππασία" },
                { id: "zip_line_day", label: "Zip line" },
                { id: "parasailing_day", label: "Parasailing" },
                { id: "sunset_watching", label: "Ηλιοβασίλεμα" },
                { id: "beach_reading", label: "Διάβασμα παραλία" },
                { id: "beach_games", label: "Παιχνίδια παραλία" }
            ]
        },
        fun_outdoor_night: {
            id: "fun_outdoor_night",
            label: "Βράδυ",
            pool: [
                { id: "beach_night", label: "Παραλία (βράδυ)" },
                { id: "stargazing", label: "Αστρονομία" },
                { id: "bonfire", label: "Φωτιά" },
                { id: "camping_night", label: "Κατασκήνωση (βράδυ)" },
                { id: "night_walk", label: "Νυχτερινή βόλτα" },
                { id: "rooftop_night", label: "Rooftop (βράδυ)" },
                { id: "outdoor_cinema", label: "Open air cinema" },
                { id: "beach_bar", label: "Beach bar" },
                { id: "moonlight_swim", label: "Κολύμπι φεγγάρι" },
                { id: "night_photography", label: "Νυχτερινή φωτογραφία" },
                { id: "night_hiking", label: "Νυχτερινή πεζοπορία" },
                { id: "night_cycling", label: "Νυχτερινή ποδηλατική" },
                { id: "night_market", label: "Νυχτερινή αγορά" },
                { id: "festival_night", label: "Φεστιβάλ (βράδυ)" },
                { id: "concert_outdoor", label: "Συναυλία (outdoor)" },
                { id: "beach_party", label: "Beach party" },
                { id: "outdoor_dining", label: "Outdoor dining" },
                { id: "rooftop_dinner", label: "Rooftop dinner" },
                { id: "garden_party", label: "Garden party" },
                { id: "terrace_bar", label: "Terrace bar" },
                { id: "sunset_cruise", label: "Sunset cruise" },
                { id: "night_cruise", label: "Night cruise" },
                { id: "night_fishing", label: "Νυχτερινό ψάρεμα" },
                { id: "lantern_walk", label: "Βόλτα με φανάρια" },
                { id: "night_tour", label: "Night tour" },
                { id: "observatory", label: "Αστεροσκοπείο" },
                { id: "glow_party", label: "Glow party" },
                { id: "full_moon_party", label: "Full moon party" },
                { id: "beach_fireworks", label: "Πυροτεχνήματα παραλία" },
                { id: "night_picnic", label: "Νυχτερινό πικνίκ" },
                { id: "night_golf", label: "Night golf" },
                { id: "night_basketball", label: "Νυχτερινό μπάσκετ" },
                { id: "night_jogging", label: "Νυχτερινό jogging" },
                { id: "night_tennis", label: "Νυχτερινό tennis" },
                { id: "midnight_swim", label: "Μέσονυχτο κολύμπι" },
                { id: "night_beach_games", label: "Νυχτερινά παιχνίδια παραλία" }
            ]
        },
        fun_indoor_relax: {
            id: "fun_indoor_relax",
            label: "Χαλαρά",
            pool: [
                { id: "cinema_indoor", label: "Σινεμά" },
                { id: "theater_indoor", label: "Θέατρο" },
                { id: "standup_indoor", label: "Stand-up comedy" },
                { id: "billiards_indoor", label: "Μπιλιάρδο" },
                { id: "bowling_indoor", label: "Bowling" },
                { id: "karaoke_indoor", label: "Karaoke" },
                { id: "escape_room_indoor", label: "Escape room" },
                { id: "board_games_indoor", label: "Επιτραπέζια" },
                { id: "game_night_indoor", label: "Game night" },
                { id: "movie_night_indoor", label: "Movie night" },
                { id: "reading_indoor", label: "Διάβασμα" },
                { id: "coffee_indoor", label: "Καφές" },
                { id: "wine_bar_indoor", label: "Wine bar" },
                { id: "brunch_indoor", label: "Brunch" },
                { id: "museum_indoor", label: "Μουσείο" },
                { id: "gallery_indoor", label: "Γκαλερί" },
                { id: "bookstore_indoor", label: "Βιβλιοπωλείο" },
                { id: "library_indoor", label: "Βιβλιοθήκη" },
                { id: "spa_indoor", label: "Spa" },
                { id: "massage_indoor", label: "Μασάζ" },
                { id: "yoga_indoor", label: "Yoga" },
                { id: "meditation_indoor", label: "Διαλογισμός" },
                { id: "cooking_indoor", label: "Μαγείρεμα" },
                { id: "baking_indoor", label: "Ζαχαροπλαστική" },
                { id: "crafting", label: "Crafting" },
                { id: "drawing_indoor", label: "Σχεδίαση" },
                { id: "painting_indoor", label: "Ζωγραφική" },
                { id: "puzzle_indoor", label: "Puzzle" },
                { id: "crossword_indoor", label: "Crossword" },
                { id: "journaling_indoor", label: "Journaling" },
                { id: "music_listening_indoor", label: "Ακούω μουσική" },
                { id: "netflix_indoor", label: "Netflix" },
                { id: "trivia_night_indoor", label: "Trivia night" },
                { id: "book_club_indoor", label: "Book club" },
                { id: "cooking_class_indoor", label: "Cooking class" },
                { id: "wine_tasting_indoor", label: "Wine tasting" }
            ]
        },
        fun_indoor_activity: {
            id: "fun_indoor_activity",
            label: "Δραστήριο",
            pool: [
                { id: "paintball_indoor", label: "Paintball" },
                { id: "laser_tag_indoor", label: "Laser tag" },
                { id: "go_karts_indoor", label: "Go-karts" },
                { id: "arcade_indoor", label: "Arcade" },
                { id: "virtual_reality_indoor", label: "Virtual reality" },
                { id: "trampoline_park_indoor", label: "Trampoline park" },
                { id: "rock_climbing_gym_indoor", label: "Rock climbing (gym)" },
                { id: "axe_throwing_indoor", label: "Axe throwing" },
                { id: "bubble_soccer_indoor", label: "Bubble soccer" },
                { id: "indoor_skydiving_activity", label: "Indoor skydiving" },
                { id: "bungee_trampoline_indoor", label: "Bungee trampoline" },
                { id: "dance_class_indoor", label: "Dance class" },
                { id: "fitness_class", label: "Fitness class" },
                { id: "boxing_class", label: "Boxing class" },
                { id: "martial_arts", label: "Martial arts" },
                { id: "pilates", label: "Pilates" },
                { id: "zumba", label: "Zumba" },
                { id: "spinning", label: "Spinning" },
                { id: "crossfit", label: "Crossfit" },
                { id: "swimming_pool", label: "Πισίνα" },
                { id: "basketball_court", label: "Κλειστό γήπεδο (μπάσκετ)" },
                { id: "football_indoor", label: "Κλειστό γήπεδο (ποδόσφαιρο)" },
                { id: "tennis_indoor", label: "Tennis (κλειστό)" },
                { id: "badminton", label: "Badminton" },
                { id: "squash", label: "Squash" },
                { id: "table_tennis", label: "Πινγκ-πονγκ" },
                { id: "volleyball_indoor", label: "Volleyball (κλειστό)" },
                { id: "ice_skating", label: "Παγοδρόμιο" },
                { id: "roller_skating", label: "Roller skating" },
                { id: "bowling_activity", label: "Bowling" },
                { id: "billiards_activity", label: "Μπιλιάρδο" },
                { id: "darts", label: "Darts" },
                { id: "escape_room_activity", label: "Escape room" },
                { id: "mini_golf_indoor", label: "Mini golf" },
                { id: "game_bar_activity", label: "Game bar" }
            ]
        }
    }
};

// Root category labels mapping
export const ROOT_CATEGORIES = {
    travel: "Ταξιδεύω",
    food: "Μαγειρεύω",
    fun: "Διασκεδάζω"
};
